"""Application packets (generate, attach, read, render) and bulk background tasks."""

import json

from conftest import SCORE_RESPONSE, FakePandoc, insert_job, wait_for_task

MODEL = "gpt-test"


def packet_response(model=MODEL):
    note = f"Generated by {model}." if model else "No attribution."
    return {
        "job_brief_markdown": f"# Brief\n{note}",
        "resume_markdown": f"# Resume\n{note}",
        "cover_letter_markdown": f"# Letter\n[site](https://example.com) [bad](javascript:alert(1)) {note}",
    }


def post(client, path, payload=None):
    return client.post(path, data=json.dumps(payload or {}), content_type="application/json")


def generate(client, job_id):
    """Start packet generation and return the finished task (tasks run synchronously in tests)."""
    response = post(client, f"/api/jobs/{job_id}/application-packet/generate")
    assert response.status_code == 202, f"generation should start as a task: {response.get_json()}"
    return wait_for_task(client, response.get_json()["task"])


class TestPacketGeneration:
    def test_generate_writes_markdown_and_docx(self, client, container, codex_runner, pandoc, workspace):
        job_id = insert_job(container, source_job_id="linkedin:1")
        codex_runner.respond(packet_response())

        task = generate(client, job_id)

        assert task["status"] == "complete", f"generation should succeed: {task}"
        packet = task["result"]["packet"]
        packet_dir = workspace / packet["path"]
        assert sorted(p.name for p in packet_dir.iterdir()) == [
            "Cover-Letter.docx",
            "Cover-Letter.md",
            "Job-Brief.docx",
            "Job-Brief.md",
            "Resume.docx",
            "Resume.md",
        ]
        job = client.get(f"/api/jobs/{job_id}").get_json()["job"]
        assert job["application_packet_path"] == packet["path"], "the packet is associated with the job"
        prompt = codex_runner.calls[0]["input"]
        assert "Use evidence only." in prompt, "packet rules from the Career Manual are included"
        assert "--sandbox" in codex_runner.calls[0]["command"]
        assert not any(p.name.startswith(".packet-staging") for p in (workspace / "applications").iterdir())

    def test_retries_once_to_add_exact_model_attribution(self, client, container, codex_runner):
        job_id = insert_job(container)
        codex_runner.respond(packet_response(model=None), model=MODEL)
        codex_runner.respond(packet_response(), model=MODEL)
        task = generate(client, job_id)
        assert task["status"] == "complete", f"the retry should succeed: {task}"
        assert "codex_generation_metadata" in codex_runner.calls[1]["input"]
        assert "-m" in codex_runner.calls[1]["command"], "retry pins the model reported by the first call"

    def test_fails_when_attribution_still_missing(self, client, container, codex_runner, workspace):
        job_id = insert_job(container)
        codex_runner.respond(packet_response(model=None))
        codex_runner.respond(packet_response(model=None))
        task = generate(client, job_id)
        assert task["status"] == "error", f"generation should fail: {task}"
        assert "attribution" in task["message"], task["message"]
        assert list((workspace / "applications").glob("*")) == [], "no partial packet is published"

    def test_fails_when_model_unreported(self, client, container, codex_runner):
        job_id = insert_job(container)
        codex_runner.respond(packet_response(), model="")
        task = generate(client, job_id)
        assert task["error_code"] == "packet_model_unreported", f"unexpected outcome: {task}"

    def test_pandoc_failure_publishes_nothing(self, config, environ, http, codex_runner, workspace):
        from conftest import FakeResolver, ImmediateThread, make_client

        from job_search.container import build_container

        container = build_container(
            config,
            environ=environ,
            http_get=http,
            codex_runner=codex_runner,
            pandoc=FakePandoc(fail_on="Resume.md"),
            thread_factory=ImmediateThread,
            resolve_host=FakeResolver(),
        )
        container.bootstrap()
        client = make_client(container)
        job_id = insert_job(container)
        codex_runner.respond(packet_response())
        task = generate(client, job_id)
        assert task["status"] == "error", f"generation should fail: {task}"
        assert "Pandoc failed for Resume.md" in task["message"], task["message"]
        assert list((workspace / "applications").glob("*")) == [], "no partial packet is published"

    def test_generate_preconditions(self, client, container, environ):
        assert post(client, "/api/jobs/999/application-packet/generate").status_code == 404
        no_url = insert_job(container, url=None)
        assert post(client, f"/api/jobs/{no_url}/application-packet/generate").status_code == 400
        attached = insert_job(container, url="https://example.com/2", application_packet_path="applications/x")
        assert post(client, f"/api/jobs/{attached}/application-packet/generate").status_code == 409
        container.runtime.update({"CODEX_CLI_PATH": "/nonexistent/codex"})
        fresh = insert_job(container, url="https://example.com/3")
        response = post(client, f"/api/jobs/{fresh}/application-packet/generate")
        assert response.status_code == 409 and "unavailable" in response.get_json()["error"]


class TestPacketFiles:
    def make_packet(self, workspace, name="2026-09-acme"):
        packet_dir = workspace / "applications" / name
        packet_dir.mkdir(parents=True)
        (packet_dir / "Resume.md").write_text("# Resume\n- <script>x</script>\n", encoding="utf-8")
        return f"applications/{name}"

    def test_attach_list_read_and_render(self, client, container, workspace):
        job_id = insert_job(container)
        path = self.make_packet(workspace)
        listed = client.get("/api/application-packets").get_json()["application_packets"]
        assert listed[0]["unassociated"] is True

        attached = post(client, f"/api/jobs/{job_id}/application-packet/attach", {"path": path}).get_json()
        assert attached["job"]["application_packet_path"] == path
        assert attached["application_packets"][0]["associated_job"]["id"] == job_id

        content = client.get(f"/api/jobs/{job_id}/application-packet/content?file=Resume.md").get_json()
        assert content["content"].startswith("# Resume")
        assert content["markdown_files"] == ["Resume.md"]

        rendered = client.get(f"/api/jobs/{job_id}/application-packet/render?file=Resume.md")
        html = rendered.get_data(as_text=True)
        assert rendered.status_code == 200 and "<h1>Resume</h1>" in html
        assert "<script>" not in html, "packet Markdown is escaped"

    def test_attach_rejects_paths_outside_applications(self, client, container, workspace):
        job_id = insert_job(container)
        response = post(client, f"/api/jobs/{job_id}/application-packet/attach", {"path": "../../etc"})
        assert response.status_code == 400
        assert post(client, f"/api/jobs/{job_id}/application-packet/attach", {"path": ""}).status_code == 400
        assert post(client, "/api/jobs/999/application-packet/attach", {"path": "x"}).status_code == 404

    def test_read_rejects_traversal_and_missing_files(self, client, container, workspace):
        path = self.make_packet(workspace)
        job_id = insert_job(container, application_packet_path=path)
        assert client.get(f"/api/jobs/{job_id}/application-packet/content?file=../x.md").status_code == 400
        assert client.get(f"/api/jobs/{job_id}/application-packet/render?file=notes.txt").status_code == 400
        assert client.get(f"/api/jobs/{job_id}/application-packet/content?file=Nope.md").status_code == 404
        unattached = insert_job(container, url="https://example.com/9")
        assert client.get(f"/api/jobs/{unattached}/application-packet/content?file=Resume.md").status_code == 404
        assert client.get("/api/jobs/999/application-packet/content?file=Resume.md").status_code == 404


class TestBulkTasks:
    def test_bulk_scoring_reports_per_item_results(self, client, container, codex_runner, enable_scoring):
        good = insert_job(container)
        bad = insert_job(container, url="https://example.com/2")
        codex_runner.respond(SCORE_RESPONSE)
        codex_runner.respond("", returncode=1)

        response = post(client, "/api/jobs/bulk/score-gpt", {"job_ids": [good, str(bad), good, 999]})

        task = response.get_json()["task"]
        assert response.status_code == 202
        task = client.get(f"/api/codex-tasks/{task['id']}").get_json()["task"]
        assert (task["status"], task["completed"], task["failed"], task["skipped"]) == ("error", 1, 1, 1)
        messages = {item["job_id"]: item["message"] for item in task["items"]}
        assert messages[good] == "Codex score 85"
        assert "exited with code 1" in messages[bad]
        assert messages[999] == "Job not found"
        assert client.get("/api/codex-tasks").get_json()["tasks"][0]["id"] == task["id"]

    def test_bulk_packets_skip_already_associated(self, client, container, codex_runner):
        attached = insert_job(container, application_packet_path="applications/x")
        fresh = insert_job(container, url="https://example.com/2")
        codex_runner.respond(packet_response())
        task = post(client, "/api/jobs/bulk/application-packets/generate", {"job_ids": [attached, fresh]}).get_json()
        task = client.get(f"/api/codex-tasks/{task['task']['id']}").get_json()["task"]
        assert (task["status"], task["completed"], task["skipped"]) == ("complete", 1, 1)

    def test_bulk_validation(self, client, enable_scoring):
        assert post(client, "/api/jobs/bulk/score-gpt", {"job_ids": []}).status_code == 400
        assert post(client, "/api/jobs/bulk/score-gpt", {"job_ids": "1"}).status_code == 400
        assert post(client, "/api/jobs/bulk/score-gpt", {"job_ids": ["x"]}).status_code == 400
        assert client.get("/api/codex-tasks/unknown").status_code == 404

    def test_bulk_scoring_requires_enabled_scoring(self, client):
        assert post(client, "/api/jobs/bulk/score-gpt", {"job_ids": [1]}).status_code == 409

    def test_unexpected_item_error_is_generic(self, container, monkeypatch, enable_scoring):
        job_id = insert_job(container)

        def crash(_job_id):
            raise RuntimeError("internal detail")

        monkeypatch.setattr(container.scoring, "populate_score", crash)
        task = container.bulk.start_scoring([job_id])
        item = container.tasks.get(task["id"])["items"][0]
        assert item["status"] == "error"
        assert "internal detail" not in item["message"]

    def test_registry_evicts_oldest_finished_tasks(self):
        from conftest import ImmediateThread

        from job_search.domain.tasks import BackgroundTaskRegistry

        registry = BackgroundTaskRegistry(max_retained=2, thread_factory=ImmediateThread)

        def finish(task_id, _job_ids):
            registry.update(task_id, status="complete")

        ids = [registry.start("op", [1], finish)["id"] for _ in range(4)]
        remaining = {task["id"] for task in registry.list()}
        assert ids[-1] in remaining and len(remaining) <= 3, "finished tasks beyond the cap are evicted"
        assert registry.update("missing") is None and registry.update_item("missing", 1) is None


class TestBackgroundCrashHandling:
    def test_worker_crash_marks_task_error_and_records_blame(self, container, monkeypatch, enable_scoring):
        from job_search.observability import METRICS

        job_id = insert_job(container)
        original_update = container.tasks.update

        def failing_update(task_id, **updates):
            if updates.get("status") == "running":
                raise RuntimeError("registry broken")
            return original_update(task_id, **updates)

        monkeypatch.setattr(container.tasks, "update", failing_update)
        before = METRICS.snapshot().get("blame.background_task_crashed", 0)
        task = container.bulk.start_scoring([job_id])
        final = container.tasks.get(task["id"])
        assert final["status"] == "error", f"a crashed worker must end the task in error: {final}"
        assert "registry broken" not in final["message"], "internal details stay in logs"
        assert METRICS.snapshot()["blame.background_task_crashed"] == before + 1, "crash must be recorded"

    def test_scheduler_loop_survives_tick_crash(self, container, monkeypatch):
        from job_search.domain.scheduler import SearchScheduler
        from job_search.observability import METRICS

        scheduler = SearchScheduler(container.db, None, 60, True, poll_seconds=0)
        calls = []

        def crashing_tick():
            calls.append(1)
            if len(calls) == 2:
                scheduler.stop()
            raise RuntimeError("tick blew up")

        monkeypatch.setattr(scheduler, "tick", crashing_tick)
        before = METRICS.snapshot().get("blame.scheduler_loop_crashed", 0)
        scheduler._loop()
        assert len(calls) == 2, "the loop keeps polling after a crash"
        assert METRICS.snapshot()["blame.scheduler_loop_crashed"] == before + 2, "each crash is recorded"

    def test_thread_excepthook_records_unhandled_exceptions(self, monkeypatch):
        import threading

        from job_search.observability import METRICS, install_thread_excepthook

        monkeypatch.setattr(threading, "excepthook", threading.excepthook)
        install_thread_excepthook()
        before = METRICS.snapshot().get("blame.thread_unhandled_exception", 0)

        def boom():
            raise ValueError("unhandled in thread")

        thread = threading.Thread(target=boom, name="test-thread")
        thread.start()
        thread.join()
        after = METRICS.snapshot().get("blame.thread_unhandled_exception", 0)
        assert after == before + 1, "uncaught thread exceptions must be recorded"


def test_pandoc_failure_response_omits_stderr(config, environ, http, codex_runner):
    import subprocess

    from conftest import FakeResolver, ImmediateThread, make_client

    from job_search.container import build_container
    from job_search.data.packet_store import PandocConverter

    failing = PandocConverter(
        which=lambda _name: "/usr/bin/pandoc",
        runner=lambda *a, **k: subprocess.CompletedProcess(a, 1, stdout="", stderr="SECRET /Users/me/tmp stderr"),
    )
    container = build_container(
        config,
        environ=environ,
        http_get=http,
        codex_runner=codex_runner,
        pandoc=failing,
        thread_factory=ImmediateThread,
        resolve_host=FakeResolver(),
    )
    container.bootstrap()
    job_id = insert_job(container)
    codex_runner.respond(packet_response())
    task = generate(make_client(container), job_id)
    assert task["error_code"] == "pandoc_conversion_failed", f"pandoc failure expected: {task}"
    assert "SECRET" not in json.dumps(task), f"stderr must not be returned to the client: {task}"


def test_codex_unavailable_message_omits_cli_path(client, container, environ):
    container.runtime.update({"CODEX_CLI_PATH": "/secret/location/codex"})
    job_id = insert_job(container)
    body = post(client, f"/api/jobs/{job_id}/application-packet/generate").get_json()
    assert "/secret/location" not in body["error"], f"the CLI path must not be returned: {body}"
